---
- name: Install nginx
  hosts: all
  become: yes
  vars:
    image: "hjaiej"
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: start nginx
      service:
        name: nginx
        state: started
    - name: debug
      debug:
        msg: "{{ image }}"
    
