- name: Install nginx
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: start nginx
      service:
        name: nginx
        state: started
    - include_vars:
        file: vars.yml
    - name: debug
      debug:
        msg: "{{ image }}"
